name: fi_base
description: "The base package for fi ([Y]et [A]nother [F]orm), written in pure dart, and has no dependency on flutter."
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  collection: ^1.0.0
  meta: ^1.0.0
dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
